[build]
  base = "hysports-app"
  command = "npm run build"
  publish = ".next"
  node_version = "18.17.0"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 